title: Hausverwaltung Marco Müller
author: Marco Müller

description: 

lang: "de"

menu:
- title: Startseite
  url: /
  weight: 1
  
- title: Onlineservice
  url: /onlineservice/
  weight: 2
  
- title: Leistungen
  url: /leistungen/
  weight: 3

- title: Verwaltung
  url: /verwaltung/
  weight: 4

- title: Nachweise und Zertifikate
  url: /nachweise-und-zertifikate/
  weight: 5

- title: Leistungsversprechen
  url: /leistungsversprechen/
  weight: 6

- title: Über mich
  url: /ueber_mich/
  weight: 7

- title: TEST - Leistungskatalog
  url: /Leistungskatalog_WEG_Verwaltung/
  weight: 8

contact:
  email: kontakt@.de

url: "test"

include: [".well-known"]
