title: Hausverwaltung Marco Müller
author: Marco Müller

description: 

lang: "de"

menu:
- title: Startseite
  url: /
  weight: 1

- title: Leistungen
  url: /leistungen/
  weight: 2

- title: Verwaltung
  url: /verwaltung/
  weight: 3

- title: Onlineservice
  url: /onlineservice/
  weight: 4

- title: Notfall-Telefon
  url: /notfall/
  weight: 5


contact:
  email: info@hausverwaltung-marcomueller.de

domain: https://hausverwaltung-marcomueller.de

include: [".well-known"]
